[2024-04-25T23:11:38.391+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T23:11:38.413+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.extract manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:11:38.554+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.extract manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:11:38.554+0000] {taskinstance.py:2303} INFO - Starting attempt 9 of 9
[2024-04-25T23:11:38.564+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract> on 2024-04-25 22:52:20.828871+00:00
[2024-04-25T23:11:38.575+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4420) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T23:11:38.575+0000] {standard_task_runner.py:63} INFO - Started process 4422 to run task
[2024-04-25T23:11:38.575+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'extract', 'manual__2024-04-25T22:52:20.828871+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpwzk4a228']
[2024-04-25T23:11:38.577+0000] {standard_task_runner.py:91} INFO - Job 193: Subtask extract
[2024-04-25T23:11:38.607+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.extract manual__2024-04-25T22:52:20.828871+00:00 [running]> on host cf1d83d83b27
[2024-04-25T23:11:38.672+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T22:52:20.828871+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T22:52:20.828871+00:00'
[2024-04-25T23:11:38.672+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T23:11:38.682+0000] {LocationConnector.py:66} INFO - Extracting data for: Guadalajara
[2024-04-25T23:11:39.116+0000] {LocationConnector.py:71} ERROR - Error querying the API
[2024-04-25T23:11:39.118+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T23:11:39.118+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 27, in extract
    metadata = location_connector.extract_location()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/LocationConnector.py", line 73, in extract_location
    df_city = pd.concat([df_city, df_city_code])
                                  ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'df_city_code' where it is not associated with a value
[2024-04-25T23:11:39.128+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pipeline, task_id=extract, execution_date=20240425T225220, start_date=20240425T231138, end_date=20240425T231139
[2024-04-25T23:11:39.139+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 193 for task extract (cannot access local variable 'df_city_code' where it is not associated with a value; 4422)
[2024-04-25T23:11:39.189+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-25T23:11:39.204+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T23:11:39.207+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
