[2024-04-25T23:21:06.483+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T23:21:06.504+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.etl.extract manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:21:06.625+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.etl.extract manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:21:06.625+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-25T23:21:06.634+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): etl.extract> on 2024-04-25 22:52:20.828871+00:00
[2024-04-25T23:21:06.642+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4774) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T23:21:06.643+0000] {standard_task_runner.py:63} INFO - Started process 4776 to run task
[2024-04-25T23:21:06.643+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'etl.extract', 'manual__2024-04-25T22:52:20.828871+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpfmri0v00']
[2024-04-25T23:21:06.645+0000] {standard_task_runner.py:91} INFO - Job 203: Subtask etl.extract
[2024-04-25T23:21:06.676+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.etl.extract manual__2024-04-25T22:52:20.828871+00:00 [running]> on host cf1d83d83b27
[2024-04-25T23:21:06.733+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='etl.extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T22:52:20.828871+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T22:52:20.828871+00:00'
[2024-04-25T23:21:06.734+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T23:21:06.746+0000] {LocationConnector.py:66} INFO - Extracting data for: Guadalajara
[2024-04-25T23:21:07.190+0000] {LocationConnector.py:71} ERROR - Error querying the API
[2024-04-25T23:21:07.191+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T23:21:07.191+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 27, in extract
    metadata = location_connector.extract_location()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/LocationConnector.py", line 73, in extract_location
    df_city = pd.concat([df_city, df_city_code])
                                  ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'df_city_code' where it is not associated with a value
[2024-04-25T23:21:07.200+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pipeline, task_id=etl.extract, execution_date=20240425T225220, start_date=20240425T232106, end_date=20240425T232107
[2024-04-25T23:21:07.208+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 203 for task etl.extract (cannot access local variable 'df_city_code' where it is not associated with a value; 4776)
[2024-04-25T23:21:07.257+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-25T23:21:07.274+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T23:21:07.277+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
