[2024-04-26T00:05:22.604+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T00:05:22.628+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.etl.extract manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-26T00:05:22.754+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.etl.extract manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-26T00:05:22.754+0000] {taskinstance.py:2303} INFO - Starting attempt 15 of 15
[2024-04-26T00:05:22.764+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): etl.extract> on 2024-04-25 22:52:20.828871+00:00
[2024-04-26T00:05:22.772+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6434) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T00:05:22.773+0000] {standard_task_runner.py:63} INFO - Started process 6442 to run task
[2024-04-26T00:05:22.772+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'etl.extract', 'manual__2024-04-25T22:52:20.828871+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpezp23j24']
[2024-04-26T00:05:22.773+0000] {standard_task_runner.py:91} INFO - Job 260: Subtask etl.extract
[2024-04-26T00:05:22.804+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.etl.extract manual__2024-04-25T22:52:20.828871+00:00 [running]> on host cf1d83d83b27
[2024-04-26T00:05:22.867+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='etl.extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T22:52:20.828871+00:00' AIRFLOW_CTX_TRY_NUMBER='15' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T22:52:20.828871+00:00'
[2024-04-26T00:05:22.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T00:05:22.878+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T00:05:22.878+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 25, in extract
    os.remove("air_quality_data.csv")
FileNotFoundError: [Errno 2] No such file or directory: 'air_quality_data.csv'
[2024-04-26T00:05:22.885+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pipeline, task_id=etl.extract, execution_date=20240425T225220, start_date=20240426T000522, end_date=20240426T000522
[2024-04-26T00:05:22.892+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 260 for task etl.extract ([Errno 2] No such file or directory: 'air_quality_data.csv'; 6442)
[2024-04-26T00:05:22.906+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T00:05:22.923+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T00:05:22.926+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
