[2024-04-24T00:07:22.534+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T00:07:22.556+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.extract manual__2024-04-24T00:07:21.400231+00:00 [queued]>
[2024-04-24T00:07:22.678+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.extract manual__2024-04-24T00:07:21.400231+00:00 [queued]>
[2024-04-24T00:07:22.679+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-24T00:07:22.687+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract> on 2024-04-24 00:07:21.400231+00:00
[2024-04-24T00:07:22.697+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1698) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-24T00:07:22.698+0000] {standard_task_runner.py:63} INFO - Started process 1700 to run task
[2024-04-24T00:07:22.697+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'extract', 'manual__2024-04-24T00:07:21.400231+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpin2y1d3z']
[2024-04-24T00:07:22.699+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask extract
[2024-04-24T00:07:22.732+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.extract manual__2024-04-24T00:07:21.400231+00:00 [running]> on host 8e318e51dc55
[2024-04-24T00:07:22.792+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T00:07:21.400231+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T00:07:21.400231+00:00'
[2024-04-24T00:07:22.792+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T00:07:22.804+0000] {LocationConnector.py:66} INFO - Extracting data for: Guadalajara
[2024-04-24T00:07:26.380+0000] {LocationConnector.py:66} INFO - Extracting data for: Monterrey
[2024-04-24T00:07:27.856+0000] {LocationConnector.py:66} INFO - Extracting data for: Mexico City
[2024-04-24T00:07:31.305+0000] {LocationConnector.py:66} INFO - Extracting data for: Puebla
[2024-04-24T00:07:33.765+0000] {LocationConnector.py:66} INFO - Extracting data for: Aguascalientes
[2024-04-24T00:07:37.210+0000] {LocationConnector.py:66} INFO - Extracting data for: Merida
[2024-04-24T00:07:38.678+0000] {LocationConnector.py:66} INFO - Extracting data for: Toluca
[2024-04-24T00:07:40.155+0000] {LocationConnector.py:66} INFO - Extracting data for: Durango
[2024-04-24T00:07:42.650+0000] {LocationConnector.py:66} INFO - Extracting data for: Chihuahua
[2024-04-24T00:07:44.141+0000] {LocationConnector.py:66} INFO - Extracting data for: San luis Potosi
[2024-04-24T00:07:45.581+0000] {LocationConnector.py:66} INFO - Extracting data for: Leon
[2024-04-24T00:07:48.059+0000] {LocationConnector.py:66} INFO - Extracting data for: Buenos Aires
[2024-04-24T00:07:49.583+0000] {LocationConnector.py:66} INFO - Extracting data for: Medellin
[2024-04-24T00:07:53.058+0000] {LocationConnector.py:78} INFO - Data extracted - Shape: (13, 12)
[2024-04-24T00:08:13.091+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-04-24T00:08:13.092+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-24T00:08:13.094+0000] {process_utils.py:132} INFO - Sending 15 to group 1700. PIDs of all processes in the group: [1700]
[2024-04-24T00:08:13.094+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1700
[2024-04-24T00:08:13.094+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-24T00:08:13.095+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T00:08:13.101+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 25, in extract
    air_quality_connector.extract_air_quality(metadata, kwargs["ds"])
  File "/opt/airflow/src/AirQualityConnector.py", line 82, in extract_air_quality
    air_quality_data = pd.json_normalize(self.get_air_quality(location[0], location[1], str(unix_start), str(unix_end)))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/AirQualityConnector.py", line 53, in get_air_quality
    response = requests.get(self.url_base, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1423, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-04-24T00:08:13.105+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pipeline, task_id=extract, execution_date=20240424T000721, start_date=20240424T000722, end_date=20240424T000813
[2024-04-24T00:08:13.113+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 73 for task extract ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(pipeline, extract, manual__2024-04-24T00:07:21.400231+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'extract', 'dag_id': 'pipeline', 'run_id': 'manual__2024-04-24T00:07:21.400231+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 4, 24, 0, 7, 22, 557152, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 4, 24, 0, 8, 13, 105237, tzinfo=Timezone('UTC')), 'duration': 50}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1700)
[2024-04-24T00:08:13.146+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1700, status='terminated', exitcode=1, started='00:07:22') (1700) terminated with exit code 1
