[2024-04-25T23:19:10.155+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T23:19:10.178+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.etl.load manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:19:10.325+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.etl.load manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:19:10.326+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-25T23:19:10.334+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): etl.load> on 2024-04-25 22:52:20.828871+00:00
[2024-04-25T23:19:10.344+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4700) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T23:19:10.345+0000] {standard_task_runner.py:63} INFO - Started process 4707 to run task
[2024-04-25T23:19:10.344+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'etl.load', 'manual__2024-04-25T22:52:20.828871+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpr1mgpbe7']
[2024-04-25T23:19:10.346+0000] {standard_task_runner.py:91} INFO - Job 200: Subtask etl.load
[2024-04-25T23:19:10.379+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.etl.load manual__2024-04-25T22:52:20.828871+00:00 [running]> on host cf1d83d83b27
[2024-04-25T23:19:10.450+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='etl.load' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T22:52:20.828871+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T22:52:20.828871+00:00'
[2024-04-25T23:19:10.450+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T23:19:10.460+0000] {RedShift.py:56} INFO - Loading data into Redshift
[2024-04-25T23:19:10.462+0000] {RedShift.py:77} INFO - Connection closed
[2024-04-25T23:19:10.462+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T23:19:10.462+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 64, in load
    redshift_loader.load_data()
  File "/opt/airflow/src/RedShift.py", line 58, in load_data
    df_air_quality = pd.read_csv("air_quality_data.csv")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'air_quality_data.csv'
[2024-04-25T23:19:10.470+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pipeline, task_id=etl.load, execution_date=20240425T225220, start_date=20240425T231910, end_date=20240425T231910
[2024-04-25T23:19:10.478+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 200 for task etl.load ([Errno 2] No such file or directory: 'air_quality_data.csv'; 4707)
[2024-04-25T23:19:10.518+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-25T23:19:10.544+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T23:19:10.545+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
