[2024-04-25T22:28:55.189+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T22:28:55.214+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [queued]>
[2024-04-25T22:28:55.222+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [queued]>
[2024-04-25T22:28:55.222+0000] {taskinstance.py:2303} INFO - Starting attempt 11 of 11
[2024-04-25T22:28:55.233+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-04-25 21:26:34.912203+00:00
[2024-04-25T22:28:55.241+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2836) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T22:28:55.242+0000] {standard_task_runner.py:63} INFO - Started process 2837 to run task
[2024-04-25T22:28:55.241+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mi_dag', 'branch_task', 'manual__2024-04-25T21:26:34.912203+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/test.py', '--cfg-path', '/tmp/tmp6oml4ml3']
[2024-04-25T22:28:55.243+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask branch_task
[2024-04-25T22:28:55.279+0000] {task_command.py:426} INFO - Running <TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [running]> on host cf1d83d83b27
[2024-04-25T22:28:55.343+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mi_dag' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T21:26:34.912203+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T21:26:34.912203+00:00'
[2024-04-25T22:28:55.343+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T22:28:55.353+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-25T22:28:55.361+0000] {logging_mixin.py:188} INFO - Estado de la tarea anterior: None
[2024-04-25T22:28:55.361+0000] {python.py:237} INFO - Done. Returned value was: tarea_fallida
[2024-04-25T22:28:55.361+0000] {branch.py:36} INFO - Branch into tarea_fallida
[2024-04-25T22:28:55.361+0000] {skipmixin.py:178} INFO - Following branch tarea_fallida
[2024-04-25T22:28:55.374+0000] {skipmixin.py:246} INFO - Skipping tasks [('tarea_exitosa', -1)]
[2024-04-25T22:28:55.390+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T22:28:55.406+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=mi_dag, task_id=branch_task, execution_date=20240425T212634, start_date=20240425T222855, end_date=20240425T222855
[2024-04-25T22:28:55.455+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-25T22:28:55.472+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T22:28:55.474+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
