[2024-04-25T23:35:26.212+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T23:35:26.233+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.test_alert manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:35:26.354+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.test_alert manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:35:26.354+0000] {taskinstance.py:2303} INFO - Starting attempt 19 of 19
[2024-04-25T23:35:26.368+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): test_alert> on 2024-04-25 22:52:20.828871+00:00
[2024-04-25T23:35:26.376+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5313) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T23:35:26.377+0000] {standard_task_runner.py:63} INFO - Started process 5315 to run task
[2024-04-25T23:35:26.376+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'test_alert', 'manual__2024-04-25T22:52:20.828871+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpke3bs8s2']
[2024-04-25T23:35:26.378+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask test_alert
[2024-04-25T23:35:26.408+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.test_alert manual__2024-04-25T22:52:20.828871+00:00 [running]> on host cf1d83d83b27
[2024-04-25T23:35:26.469+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='test_alert' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T22:52:20.828871+00:00' AIRFLOW_CTX_TRY_NUMBER='19' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T22:52:20.828871+00:00'
[2024-04-25T23:35:26.470+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T23:35:26.480+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T23:35:26.480+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 73, in check_pipeline_success
    task_instances = dag_run.get_task_instances_in_dag_run(include_failed=False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DagRun' object has no attribute 'get_task_instances_in_dag_run'
[2024-04-25T23:35:26.490+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pipeline, task_id=test_alert, execution_date=20240425T225220, start_date=20240425T233526, end_date=20240425T233526
[2024-04-25T23:35:26.497+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 220 for task test_alert ('DagRun' object has no attribute 'get_task_instances_in_dag_run'; 5315)
[2024-04-25T23:35:26.510+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-25T23:35:26.522+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T23:35:26.523+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
