[2024-04-25T23:06:42.640+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T23:06:42.666+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.test_alert manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:06:42.792+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.test_alert manual__2024-04-25T22:52:20.828871+00:00 [queued]>
[2024-04-25T23:06:42.792+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 5
[2024-04-25T23:06:42.800+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): test_alert> on 2024-04-25 22:52:20.828871+00:00
[2024-04-25T23:06:42.808+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4215) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T23:06:42.809+0000] {standard_task_runner.py:63} INFO - Started process 4217 to run task
[2024-04-25T23:06:42.809+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'test_alert', 'manual__2024-04-25T22:52:20.828871+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpiau_hwfv']
[2024-04-25T23:06:42.811+0000] {standard_task_runner.py:91} INFO - Job 181: Subtask test_alert
[2024-04-25T23:06:42.845+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.test_alert manual__2024-04-25T22:52:20.828871+00:00 [running]> on host cf1d83d83b27
[2024-04-25T23:06:42.911+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='test_alert' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T22:52:20.828871+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T22:52:20.828871+00:00'
[2024-04-25T23:06:42.912+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T23:06:42.923+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T23:06:42.923+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 77, in alert_notification
    os.remove("air_data.json")
FileNotFoundError: [Errno 2] No such file or directory: 'air_data.json'
[2024-04-25T23:06:42.931+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pipeline, task_id=test_alert, execution_date=20240425T225220, start_date=20240425T230642, end_date=20240425T230642
[2024-04-25T23:06:42.938+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 181 for task test_alert ([Errno 2] No such file or directory: 'air_data.json'; 4217)
[2024-04-25T23:06:42.982+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-25T23:06:42.994+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T23:06:42.995+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
